blank_issues_enabled: false
contact_links:
  - name: Документация
    url: https://github.com/VseMirka200/multifora/blob/main/docs/README.md
    about: Перед созданием обращения проверьте руководства и решение проблем.
