# -*- coding: utf-8 -*-

SPACE_NONE = 0
SPACE_XXS = 1
SPACE_XS = 2
SPACE_SM = 4
SPACE_MD = 6
SPACE_LG = 8
SPACE_XL = 10
SPACE_2XL = 12
SPACE_3XL = 14

MARGINS_NONE = (0, 0, 0, 0)
APP_MARGINS = (0, 0, SPACE_SM, 6)
CARD_MARGINS = (0, 6, 0, 6)
CARD_MARGINS_TIGHT_BOTTOM = (0, 6, 0, 5)
DIALOG_MARGINS = (12, 12, 12, 12)
MESSAGE_DIALOG_MARGINS = (14, 12, 14, 12)
PARAM_BLOCK_MARGINS = (0, 2, 0, 2)
DROP_ZONE_MARGINS = (0, 8, 0, 8)
TOP_MENU_MARGINS = (0, 2, 0, 2)
SETTINGS_PANEL_MARGINS = (0, 0, 0, 0)
SETTINGS_PANEL_COLUMN_GAP = SPACE_LG
OPERATIONS_PAGE_MARGINS = (0, 0, 0, 0)

FIELD_HEIGHT = 20
HEADER_FIELD_HEIGHT = 20
CONTROL_HEIGHT = 24
HEADER_CONTROL_HEIGHT = 28
PROGRESS_HEIGHT = 22
LINK_BUTTON_HEIGHT = 22
SECTION_BUTTON_HEIGHT = 34
TAB_BAR_HEIGHT = 36
CHECKBOX_SIZE = 16

MENU_ITEM_PADDING = "4px 8px"
BUTTON_PADDING = "3px 10px"
HEADER_CELL_PADDING = "2px 10px"
LINK_BUTTON_PADDING = "2px 8px"
INPUT_PADDING = "3px"


def px(value: int) -> str:
    return f"{int(value)}px"


def padding(vertical: int, horizontal: int) -> str:
    return f"{int(vertical)}px {int(horizontal)}px"
